### PR TITLE
Translate Java solution to Clojure

### PR DESCRIPTION
**Pull request by serioga**

### CODE REVIEW

**Review by niklas-heer — APPROVED** [review]

**Comment by niklas-heer** [comment]
Very interesting results. It made Clojure faster, but Clojure via Babashka slower 🤔 😅 
combined_results

**Comment by niklas-heer** [comment]
@serioga thank you very much for your contribution!
In general, I think I choose speed improvements done to the "main implementation" of a language rather than something like Babashka and PyPy.

**Comment by serioga** [comment]
Probably you measure app starting time, which is slower for Clojure comparing to Java

**Comment by niklas-heer** [comment]
@serioga yes that is correct, currently startup and IO are included. There are some thoughts (#59) of getting "clean" data just for computing pi, but nothing is implemented yet.

**Comment by serioga** [comment]
OK, but for Clojure those figures are misleading :-)

**Comment by serioga** [comment]
In my tests this code was executed in about 400 ms.
And previous one was about 2500 ms.
Also Java warms up and works faster after this :-)

**Comment by niklas-heer** [comment]
It depends on what you use Clojure for. For a long-running application, I agree. For a CLI application which is invoked from time to time, it's closer to what can be expected, imho.

**Comment by niklas-heer** [comment]
I think that is why I would like to capture both data with startup and IO and just plain pi calculation in the future.

**Comment by serioga** [comment]
I would test nbb for CLI application.
Also I would test something more long running (what requires tens seconds) to reduce significance of startup time.
For startup time I would make separate test with zero op script, to measure which solutions are faster for launching short-term CLI apps.

**Comment by giordano** [comment]
Note that we had been advocating for this kind of changes in #13, #22, #35, etc... 🙂

**Pull request merged**
