### PR TITLE
vectorized R

### PR DESCRIPTION
**Pull request by jonocarroll**

### CODE REVIEW

**Comment by jonocarroll** [comment]
(simple PR via the web interface). I haven't run the comparison myself, but if that's possible via CI prior to merge it would be useful to review.

**Review by niklas-heer — APPROVED** [review]
Looks good to me, let's see what the CI says.

**Comment by jonocarroll** [comment]
The speedup is about what I predicted, though I suppose my M1 mac runs a bit quicker than the CI.

combined_results

**Comment by niklas-heer** [comment]
That is true, it's a 2-core Ubuntu machine AFAIK. 
Thank you for your contribution @jonocarroll :+1:

**Comment by Moelf** [comment]
isn't vectorized R calling the underlying library? this shouldn't be allowed because then Python would use Numpy?

**Comment by niklas-heer** [comment]
As far as I understand it, it is part of the standard library of R which would be the deciding factor for me. Whereas NumPy is an additional package which would need to be installed. Correct me if I'm wrong.

**Comment by jonocarroll** [comment]
R is vectorised by design in the sense that operations like `a + b` (in this case, the division and `sum()`) can take vectors without users needing to write a loop. There _is_ of course a loop, but it happens in the internals. I actually have a post on this: https://jcarroll.com.au/2022/04/22/where-for-loop-art-thou/

**Pull request merged**
