### PR TITLE
AVX2 variation of c++

### PR DESCRIPTION
**Pull request by joelandman**
Use `-march=native -O` to enable.

### CODE REVIEW

**Comment by joelandman** [comment]
Added an unrolled julia with simplified loops/execution.

**Comment by niklas-heer** [comment]
First thank you @joelandman.
The question for me is what do you intend with the program code? Is it to be added as separate runs alongside the rest or to be execute instead of the current implementations?

**Comment by joelandman** [comment]
I would suggest a separate run.  I was curious as to whether I could vectorize this code using AVX2.  This is a naive 1st pass.

**Comment by joelandman** [comment]
Note that for the julia code, I wanted to see if simplifying it  and unrolling it would have an impact.   It looks like it is noticeable, in part due to the impact of reducing the number of loop test conditionals.

**Comment by niklas-heer** [comment]
That is fair enough. To run your code new entries have to be added to the `Earthfile`.

If you need help with implementing that let me know. Then I can do that for you. Otherwise if you want to give it a shot here are two relevant examples:

https://github.com/niklas-heer/speed-comparison/blob/769babc00014ac3456c877a196f7fb53b4140912/Earthfile#L109-L115

https://github.com/niklas-heer/speed-comparison/blob/769babc00014ac3456c877a196f7fb53b4140912/Earthfile#L201-L209

**Comment by joelandman** [comment]
Ok, let me play with this, and if I can get it working here, I'll add this to the PR.

**Comment by joelandman** [comment]
Updated Earthfile to include c++-avx2, and julia_ux4

**Review by niklas-heer — APPROVED** [review]
I've just changed the --lang parameter, as it is the name used to name the y-axis of the plot.
Let's see what the CI says.

**Review by niklas-heer — APPROVED** [review]

**Review by niklas-heer — APPROVED** [review]

**Review by niklas-heer — APPROVED** [review]

**Comment by joelandman** [comment]
Interesting.  On my machine (Epyc 7551 Zen1 AMD), they are about 2x faster for the AVX, and 33% faster for Julia.  I'll try to replicate this on the alpine distro (I use debian 11 on my machine).

**Comment by Moelf** [comment]
> The Julia solutions seems to be a bit slower than the standard solution.

iteration too little, start up time dominate

**Comment by niklas-heer** [comment]
> > The Julia solutions seems to be a bit slower than the standard solution.
> 
> iteration too little, start up time dominate

That could be it. I don't know yet when I will get around to start implementing #59.

**Comment by joelandman** [comment]
I could do this easily for Julia.  Might be harder for C++ (as startup is minimal).  The reason I thought the julia unroll is faster, is this:

Original:
```
julia> using BenchmarkTools
julia> struct SignVector <: AbstractVector{Float64}
           len::Int
       end
julia> Base.size(s::SignVector) = (s.len,)
julia> Base.getindex(::SignVector, i::Int) = Float64((-1)^iseven(i))
julia> function f(rounds)
           xs = SignVector(rounds + 2)
           pi = 1.0
           @simd for i in 2:(rounds + 2)
               x = xs[i]
               pi += x / (2 * i - 1)
           end
           return pi*4
       end
f (generic function with 1 method)
julia> rounds = parse(Int64, readchomp("rounds.txt"))
100000000
julia> f(rounds)
3.1415926435880532
julia> @benchmark f(rounds)
BenchmarkTools.Trial: 36 samples with 1 evaluation.
 Range (min … max):  142.441 ms … 145.558 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     142.733 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   142.835 ms ± 493.724 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

       █▃  ▁                                                     
  ▆▆▆▆▇██▆▁█▇▄▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄ ▁
  142 ms           Histogram: frequency by time          146 ms <

 Memory estimate: 16 bytes, allocs estimate: 1.
```

Unrolled:
```
julia> using BenchmarkTools
julia> function f(rounds)
           pi = 1.0
           x  = -1.0
           r2 = rounds + 2
           vend = r2 - r2 % 4
           @simd for i in 2:4:r2
               pi +=   x / (2.0 * i -  1.0) - 
                       x / (2.0 * i +  1.0) + 
                       x / (2.0 * i +  3.0) - 
                       x / (2.0 * i +  5.0) 
           end
           for i in vend+1:r2
                  pi += 1.0 / (2.0 * (i + 0.0) - 1.0)
               x = -x
           end
           return pi*4
       end
f (generic function with 1 method)
julia> rounds = parse(Int64, readchomp("rounds.txt"))
100000000
julia> print(f(rounds))
3.141592703611381
julia> @benchmark f(rounds)
BenchmarkTools.Trial: 57 samples with 1 evaluation.
 Range (min … max):  88.304 ms …  90.359 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     88.341 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   88.379 ms ± 267.732 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

          ▅     ▂   █ ▅                                         
  ▅▁▁▅▁▅▁▅███▅▅▅█▁▁▁████▅▁▁███▅█▅███▁▅▅▁█▅▁▁▅▁▁▁▁▁▁▁▅▁▁▁▁▁▁▁▁▅ ▁
  88.3 ms         Histogram: frequency by time         88.4 ms <

 Memory estimate: 16 bytes, allocs estimate: 1.
```

The unrolled is nearly 2x the speed of the plain.  Similarly for the cpp versions

```
joe@calculon:~/bench/speed-comparison/src$ gcc -O3 -march=native leibniz.cpp -o l.x
joe@calculon:~/bench/speed-comparison/src$ gcc -O3 -march=native leibniz_avx2.cpp -o l_avx2.x
joe@calculon:~/bench/speed-comparison/src$ /usr/bin/time ./l.x
3.1415926635893259
0.26user 0.00system **0:00.26elapsed** 100%CPU (0avgtext+0avgdata 1388maxresident)k
1inputs+0outputs (4major+66minor)pagefaults 0swaps
joe@calculon:~/bench/speed-comparison/src$ /usr/bin/time ./l_avx2.x
3.1415926635945883
0.11user 0.00system **0:00.11elapsed** 98%CPU (0avgtext+0avgdata 1460maxresident)k
1inputs+0outputs (4major+70minor)pagefaults 0swaps

```

showing that the avx2 version was a little more than 2x the performance of the regular cpp version.

I'm not sure what the differences are, though my machine is running debian 11 (and therefore glibc), and the test cases for c++ are running on alpine and musl.  I've lit up an alpine VM on that machine (using kvm) to see if I can compare, and maybe generate insight.  I've heard anecdotally about performance differences, but haven't measured them.

**Comment by Moelf** [comment]
>julia> @benchmark f(rounds)

yeah but this is not how this repo does timing, this repo calls
```
julia lebniz.jl
```

which includes 200ms or something start uptime and compile first run time. And the CI system is very unstable, all of the top languages should be exactly the same

**Pull request merged**
